schemes:
  cubic:
    name: TCP Cubic
    color: black
    marker: 'v'
  vegas:
    name: TCP Vegas
    color: silver
    marker: 'h'
  bbr:
    name: TCP BBR
    color: gold
    marker: '^'
  copa:
    name: Copa
    color: red
    marker: 'o'
  vivace:
    name: PCC-Vivace
    color: blue
    marker: '<'
  pcc:
    name: PCC-Allegro
    color: orange
    marker: '+'
  PDCC:
    name: PDCC
    color: green
    marker: '*'
